version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'desafio'
      MYSQL_ROOT_PASSWORD: 'desafio'
    ports:
      - '13306:3306'
    expose:
      - '13306'
    volumes:
      - ./MySql:/var/lib/mysql
  
  backend:
    env_file:
      - ./backend/.env
    build:
      context: ./backend
    ports:
      - '5000:5000'
