"""

Revision ID: 5569c03c5982
Revises: 184d6a7932b7
Create Date: 2022-01-31 12:09:34.078089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5569c03c5982'
down_revision = '184d6a7932b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
