"""

Revision ID: 757d7082bd5a
Revises: 5569c03c5982
Create Date: 2022-01-31 12:21:43.709156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757d7082bd5a'
down_revision = '5569c03c5982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cards', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'tag_id')
    # ### end Alembic commands ###
